### ISSUE TITLE
я хорошшо сходил нармально навалил... Нормально НАВалИл

### ISSUE THREAD

**Issue by Mopsik62** [Djivs/img-to-pdf#2]

**Comment by dj1vs** [comment]
Ребята, когда же вы уже поймёте, что Цой - это устаревшая фигня. Этот недопанк и рядом не стоит с Моргенштерном. Ну камон, слушать цоя в 2к20 году это полный кринж... Я когда вижу людей, слушающих Цоя, пробиваю свое лицо фейспалмом. Просто сравните трек Моргена и песню Цоя, например: кадиллак и пачка сигарет. В первом варианте всё звучит ново и хайпово, крутые биты и рифмы. А во втором случае... Ну это просто дикий факап... О чем вообще думал Цой когда записывал это говнище? Хреновое качество звука, бессмысленные текста, херовый голос, как-будто у него какой-то комок шерсти в горле застрял и он как кот пытается выхаркать шерсть. В общем, ребят, перестаньте слушать это говнище и продвигайтесь вперёд. Надеюсь, вы меня услышали и действительно перестанете слушать говнище и станете слушать реальную музыку.
